### ISSUE TITLE
Server less function crashed.

### ISSUE THREAD

**Issue by Calm1403** [NotCookey/QuotenJoke-Api#1]
Hey, the api is returning an internal error status code - If you've stopped the development of this api, sorry for creating this issue, but if you've not I'd encourage you to check it out because I really like using this!

![image](https://github.com/NotCookey/QuotenJoke-Api/assets/105587941/49a3ba62-6227-47e3-8393-609aff238ad7)

**Comment by NotCookey** [comment]
Thx for informing me. Its been a long time since i've updated the api something must have gone wrong in the backend. I'll check it out and fix it.

**Comment by Calm1403** [comment]
@NotCookey Awesome, I've been using this for a discord bot because I thought I'd include a couple APIs for a bit of fun.

**Comment by NotCookey** [comment]
I've fixed it. There were some issues with Vercel so I've deployed it on a different hosting and the url had been changed. 

> New Url : https://quotenjoke.onrender.com

Everything else remains the same like the routes.

**Comment by Calm1403** [comment]
@NotCookey Brilliant, I look forward to using it!
